SELECT A.ACTOR_ID AS "ID",
	A.FIRST_NAME AS "First name",
	A.LAST_NAME AS "Last name",
	COUNT(R.RENTAL_ID) AS "Rental quantity"
FROM FILM_ACTOR FA
JOIN ACTOR A ON FA.ACTOR_ID = A.ACTOR_ID
JOIN INVENTORY I ON FA.FILM_ID = I.FILM_ID
JOIN RENTAL R ON R.INVENTORY_ID = I.INVENTORY_ID
GROUP BY A.ACTOR_ID
ORDER BY COUNT(R.RENTAL_ID) DESC
LIMIT 10