SELECT C.CITY,
	SUM(CT.ACTIVE) AS "Active",
	(COUNT(CT.CUSTOMER_ID) - SUM(CT.ACTIVE)) AS "Not Active"
FROM ADDRESS A
JOIN CITY C ON C.CITY_ID = A.CITY_ID
JOIN CUSTOMER CT ON CT.ADDRESS_ID = A.ADDRESS_ID
GROUP BY C.CITY
ORDER BY (COUNT(CT.CUSTOMER_ID) - SUM(CT.ACTIVE)) DESC