SELECT A.FIRST_NAME,
	A.LAST_NAME,
	COUNT (FC.FILM_ID)
FROM FILM_ACTOR FA
JOIN FILM_CATEGORY FC ON FC.FILM_ID = FA.FILM_ID
JOIN CATEGORY C ON C.CATEGORY_ID = FC.CATEGORY_ID
JOIN ACTOR A ON A.ACTOR_ID = FA.ACTOR_ID
WHERE C.NAME = 'Children'
GROUP BY A.FIRST_NAME,
	A.LAST_NAME
HAVING COUNT (FC.FILM_ID) in
		(SELECT DISTINCT COUNT (FC.FILM_ID)
			FROM FILM_ACTOR FA
			JOIN FILM_CATEGORY FC ON FC.FILM_ID = FA.FILM_ID
			JOIN CATEGORY C ON C.CATEGORY_ID = FC.CATEGORY_ID
			WHERE C.NAME = 'Children'
			GROUP BY FA.ACTOR_ID
			ORDER BY COUNT (FC.FILM_ID) DESC
			LIMIT 3)
ORDER BY COUNT (FC.FILM_ID) DESC