SELECT Q1.CITY,
	MAX(Q1.SUM_HOURS)
FROM
	(SELECT CT.CITY AS CITY,
			CAT.NAME AS CATEGORY,
			SUM(DATE_PART('hour',RETURN_DATE - RENTAL_DATE)) AS SUM_HOURS
		FROM RENTAL R
		JOIN INVENTORY I ON I.INVENTORY_ID = R.INVENTORY_ID
		JOIN FILM_CATEGORY FC ON FC.FILM_ID = I.FILM_ID
		JOIN CUSTOMER C ON C.CUSTOMER_ID = R.CUSTOMER_ID
		JOIN ADDRESS A ON A.ADDRESS_ID = C.ADDRESS_ID
		JOIN CITY CT ON CT.CITY_ID = A.CITY_ID
		JOIN CATEGORY CAT ON CAT.CATEGORY_ID = FC.CATEGORY_ID
		WHERE CT.CITY like 'a%'
		GROUP BY CT.CITY,
			CAT.NAME
		ORDER BY CT.CITY,
			SUM(DATE_PART('hour',RETURN_DATE - RENTAL_DATE)) DESC) Q1
GROUP BY Q1.CITY
UNION
SELECT Q2.CITY,
	MAX(Q2.SUM_HOURS)
	
FROM
	(SELECT CT.CITY AS CITY,
			CAT.NAME AS CATEGORY,
			SUM(DATE_PART('hour',RETURN_DATE - RENTAL_DATE)) AS SUM_HOURS
		FROM RENTAL R
		JOIN INVENTORY I ON I.INVENTORY_ID = R.INVENTORY_ID
		JOIN FILM_CATEGORY FC ON FC.FILM_ID = I.FILM_ID
		JOIN CUSTOMER C ON C.CUSTOMER_ID = R.CUSTOMER_ID
		JOIN ADDRESS A ON A.ADDRESS_ID = C.ADDRESS_ID
		JOIN CITY CT ON CT.CITY_ID = A.CITY_ID
		JOIN CATEGORY CAT ON CAT.CATEGORY_ID = FC.CATEGORY_ID
		WHERE CT.CITY like '%-%'
		GROUP BY CT.CITY,
			CAT.NAME
		ORDER BY CT.CITY,
			SUM(DATE_PART('hour',RETURN_DATE - RENTAL_DATE)) DESC) Q2
GROUP BY Q2.CITY
order by city, max desc